[tool.poetry]
name = "poetry add jazzmin"
version = "0.1.0"
description = ""
authors = ["Harshit2973 <harshit3789.be21@chitkara.edu.in>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
